version: '3.7'
services:
  server:
    build:
      context: ./backend/
    command: npm start
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3333:3333"
  client:
    build:
      context: ./web/
    command: npm start
    volumes:
      - ./web/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"